kind: Service
apiVersion: v1
metadata:
  name: parquet-oci
  labels:
    app: parquet-oci
spec:
  type: NodePort
  selector:
    app: parquet-oci
  ports:
    - port: 8080
      targetPort: 8080
      name: http
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: parquet-oci
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: parquet-oci
        version: v1
    spec:
      containers:
        - name: parquet-oci
          image: parquet-oci
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---